### ISSUE TITLE
Does not initialize properly on PowerShell Core

### ISSUE THREAD

**Issue by mpodwysocki** [badmotorfinger/z#40]
Using PowerShell Core, currently version 6.1.1, z does not initialize properly with the following error:

```powershell
Cannot index into a null array.
At C:\Program Files\PowerShell\Modules\z\1.1.9\z.psm1:655 char:1
+ $global:options['CustomArgumentCompleters']['z:JumpPath'] = $Completi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : NullArray
```

Reproduction Steps:
```
Install-Module -Name z
Import-Module z
```

Workaround steps is to initialize the dictionary properly for the CustomArgumentCompleters:
```powershell
if (-not $global:options['CustomArgumentCompleters']) { 
  $global:options = @{CustomArgumentCompleters = @{}} 
}
```

What should be the proper answer here?

**Comment by vincpa** [comment]
This does not happen for "normal" Powershell. I also do not have Powershell Core install. Happy to accept a pull request for this :)

**Comment by marcinsmialek** [comment]
There are no issues with current z and PS Core 7
