### ISSUE TITLE
Change the z to other key

### ISSUE THREAD

**Issue by gabrielnemeth** [badmotorfinger/z#53]
Hey, new powershell user here. Is it possible to set up a different key?

**Comment by badmotorfinger** [comment]
Yes it is possible. Line 63 of z.psm1 you'd change the function name from `z` to whatever other key you'd like to use and you also need to change line 663 `-Function z` to `-Function <other key>`

It would be nice if this was configurable, however, I don't have the time to do this.

Pull requests welcome :)
