### ISSUE TITLE
Slow Z folder find is sometimes slow

### ISSUE THREAD

**Issue by coinzdude** [badmotorfinger/z#54]
Is there a debug mode for Z that I can try to see why it's hanging to switch to a particular folder?  

I did a z -clean but it did not help

**Comment by badmotorfinger** [comment]
No but that's a great idea.

What can you tell me about this particular folder? How many files are in there? What's it called? What happens when you `cd` into this folder manually?

**Comment by badmotorfinger** [comment]
Closed due to inactivity
