### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by argvrutter** [badmotorfinger/z#56]

**Comment by badmotorfinger** [comment]
This is a power shell script which essentially reads and writes to a text file. It doesn't need a license.

Copy it, do whatever you want.

**Comment by argvrutter** [comment]
That would be illegal based on US copyright law. I’d like to have this
approved for use at my workplace. If you don’t care about how people use
this I’d recommend using the MIT license.

**Comment by badmotorfinger** [comment]
License added
