### ISSUE TITLE
no new directories can be added to the history

### ISSUE THREAD

**Issue by hpp0hpp** [badmotorfinger/z#59]
no new directories can be added to the history

![image](https://user-images.githubusercontent.com/54829297/205663795-9d65b878-bc33-4d6e-944d-6bac830b7d51.png)

**Comment by badmotorfinger** [comment]
Can you please type in `Import-Module z` at the command line and then try again?

**Comment by hpp0hpp** [comment]
@badmotorfinger 

doesn't work, even though I put it in the profile

![image](https://user-images.githubusercontent.com/54829297/206073521-1f105602-fe43-4bd9-917e-967780b62220.png)

**Comment by badmotorfinger** [comment]
I suspect this might have something to do with a new version of PowerShell perhaps.

No other users have reported this.

Can you please try one more thank for me, what happens when you type in `cdX` ?

**Comment by hpp0hpp** [comment]
> I suspect this might have something to do with a new version of PowerShell perhaps.
> 
> No other users have reported this.
> 
> Can you please try one more thank for me, what happens when you type in `cdX` ?


nothing happens

![image](https://user-images.githubusercontent.com/54829297/206854249-9ca847e7-f989-4404-82d6-6bd540cf53aa.png)

**Comment by hpp0hpp** [comment]
I've updated to pwsh 1.7.3, and here I attached my profile if it helps.

![image](https://user-images.githubusercontent.com/54829297/206854520-194855d6-6470-4dcd-bb33-6996aeea1663.png)

`Import-Module z
oh-my-posh init pwsh | Invoke-Expression

#-------------------------------  Set Hot-keys BEGIN  -------------------------------
# 设置预测文本来源为历史记录
Set-PSReadLineOption -PredictionSource History

# 每次回溯输入历史，光标定位于输入内容末尾
Set-PSReadLineOption -HistorySearchCursorMovesToEnd

# 设置 Tab 为菜单补全和 Intellisense
Set-PSReadLineKeyHandler -Key "Tab" -Function MenuComplete

# 设置 Ctrl+d 为退出 PowerShell
Set-PSReadlineKeyHandler -Key "Ctrl+d" -Function ViExit

# 设置 Ctrl+z 为撤销
Set-PSReadLineKeyHandler -Key "Ctrl+z" -Function Undo

# 设置向上键为后向搜索历史记录
Set-PSReadLineKeyHandler -Key UpArrow -Function HistorySearchBackward

# 设置向下键为前向搜索历史纪录
Set-PSReadLineKeyHandler -Key DownArrow -Function HistorySearchForward
#-------------------------------  Set Hot-keys END    -------------------------------





#-------------------------------    Functions BEGIN   -------------------------------
# Python 直接执行
$env:PATHEXT += ";.py"

# 更新系统组件
function Update-Packages {
	# update pip
	Write-Host "Step 1: 更新 pip" -ForegroundColor Magenta -BackgroundColor Cyan
	$a = pip list --outdated
	$num_package = $a.Length - 2
	for ($i = 0; $i -lt $num_package; $i++) {
		$tmp = ($a[2 + $i].Split(" "))[0]
		pip install -U $tmp
	}

	# update TeX Live
	$CurrentYear = Get-Date -Format yyyy
	Write-Host "Step 2: 更新 TeX Live" $CurrentYear -ForegroundColor Magenta -BackgroundColor Cyan
	tlmgr update --self
	tlmgr update --all

	# update Chocolotey
	Write-Host "Step 3: 更新 Chocolatey" -ForegroundColor Magenta -BackgroundColor Cyan
	choco outdated
}
#-------------------------------    Functions END     -------------------------------





#-------------------------------   Set Alias BEGIN    -------------------------------
# 1. 编译函数 make
function MakeThings {
	nmake.exe $args -nologo
}
Set-Alias -Name make -Value MakeThings

# 2. 更新系统 os-update
Set-Alias -Name os-update -Value Update-Packages

# 3. 查看目录 ls & ll
function ListDirectory {
	(Get-ChildItem).Name
	Write-Host("")
}
Set-Alias -Name ls -Value ListDirectory
Set-Alias -Name ll -Value Get-ChildItem

# 4. 打开当前工作目录
function OpenCurrentFolder {
	param
	(
		# 输入要打开的路径
		# 用法示例：open C:\
		# 默认路径：当前工作文件夹
		$Path = '.'
	)
	Invoke-Item $Path
}
Set-Alias -Name open -Value OpenCurrentFolder
#-------------------------------    Set Alias END     -------------------------------





#-------------------------------   Set Network BEGIN    -------------------------------
# 1. 获取所有 Network Interface
function Get-AllNic {
	Get-NetAdapter | Sort-Object -Property MacAddress
}
Set-Alias -Name getnic -Value Get-AllNic

# 2. 获取 IPv4 关键路由
function Get-IPv4Routes {
	Get-NetRoute -AddressFamily IPv4 | Where-Object -FilterScript {$_.NextHop -ne '0.0.0.0'}
}
Set-Alias -Name getip -Value Get-IPv4Routes

# 3. 获取 IPv6 关键路由
function Get-IPv6Routes {
	Get-NetRoute -AddressFamily IPv6 | Where-Object -FilterScript {$_.NextHop -ne '::'}
}
Set-Alias -Name getip6 -Value Get-IPv6Routes
#-------------------------------    Set Network END     -------------------------------`

**Comment by hpp0hpp** [comment]
this is in .cdhistory

`
0007.00638063702056715598D:\projects
0003.00638063699257319428C:\Users\hpp0h
0003.00638063055888348071D:\projects\M-videoparse\python-backed
0004.00638063066555808367D:\mysites\shenma

`

**Comment by badmotorfinger** [comment]
OK, try this.

Start a new PowerShell instance like this

`PowerShell –noprofile`

Then, type `Import-Module z`

Then try `cd projects` and `z project`

**Comment by hpp0hpp** [comment]
> PowerShell –noprofile

it has something to do with my profile. after I comment out line by line, it shows that may have some conflicts with oh-my-posh

after I comment # oh-my-posh init pwsh | Invoke-Expression

seems the problem solved

**Comment by badmotorfinger** [comment]
You might want to try and debug the issue? Sorry I could help more.
