### ISSUE TITLE
Can't -Remove a dir if it no longer exists

### ISSUE THREAD

**Issue by Stan-Stani** [badmotorfinger/z#64]
I can't remove a dir from z's memory if the dir no longer exists, as it's not possible to navigate to the dir in question and then use -Remove

**Comment by badmotorfinger** [comment]
Apologies for the late reply.

You can clear unreachable directories by doing a `z -clear`

**Comment by deadcoder0904** [comment]
@badmotorfinger i did clean it but it still shows up in autocomplete/history even after reopening the shell. maybe a bug?
