### ISSUE TITLE
System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.

### ISSUE THREAD

**Issue by yahiaAz201** [badmotorfinger/z#65]
i was using it without any problem, now am having this annoying error any help ?

![image](https://github.com/badmotorfinger/z/assets/66499992/a1f45056-b5fa-4525-a725-e60171db33cb)

**Comment by badmotorfinger** [comment]
Hi,
 I am currently away for a few says. Will reply end of week 👍

-------- Original Message --------

**Comment by badmotorfinger** [comment]
@yahiaAz201 - If this has been working and then it suddenly stopped, then something has changed. My best guess here is that another powershell module you recently installed perhaps broke it, but I'm not sure.

Are you aware of any recent changes to your system? PowerShell updates perhaps or even windows updates?

**Comment by yahiaAz201** [comment]
no i didn't install any powershell module

**Comment by badmotorfinger** [comment]
This is currently not an issue on any other system.

My suggestion here is, disable all modules except for `z`. See if it works, if it does, then slowly re-enable other modules one by one until you find the conflicting module.
